# Site
repository: jojoldu/jojoldu.github.io
# favicon: images/favicon.ico

# Personal info
name: 박준영
title: 웹개발자
email: nkooog@naver.com
# website: https://jojoldu.tistory.com

# Social links
# twitter_username: jojoldu
github_username:  nkooog
# dribbble_username: jekyll
# facebook_username: jojoldu
# flickr_username: jekyll
# linkedin_username: jojoldu
# pinterest_username: jekyll
# youtube_username: UCSEOUzkGNCT_29EU_vnBYjg

# About Section
about_title: 자기소개
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 <h2>안녕하세요, 박준영입니다.</h2> <br><br>
 9년 차 웹 개발자로 공공기관 기록물 관리시스템 전문의 한국문헌정보기술, 클라우드 서비스 기반 CRM  브로드씨엔에스 에서 백엔드 및 웹 서비스 개발 및 유지보수 업무 등을 담당하고 있습니다.
 팀원들과 협력하여 더 나은 환경과 우수한 시스템을 개발하는 데 큰 만족감을 느끼며 업무 수행하며, 더 나은 코드를 위해 팀원 간의 소통을 중요시합니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
