# Site
repository: jojoldu/jojoldu.github.io
# favicon: images/favicon.ico

# Personal info
name: 박준영
title: 웹개발자
email: nkooog@naver.com
# website: https://jojoldu.tistory.com

# Social links
# twitter_username: jojoldu
github_username:  nkooog
# dribbble_username: jekyll
# facebook_username: jojoldu
# flickr_username: jekyll
# linkedin_username: jojoldu
# pinterest_username: jekyll
# youtube_username: UCSEOUzkGNCT_29EU_vnBYjg

# About Section
about_title: 자기소개
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  <p>Java &amp; 전자정부 / SpringBoot &amp; Apache, Tomcat 기반의 9년차 웹 개발자로
          <strong>공공기관 기록물관리시스템 전문</strong>의 한국문헌정보기술, <strong>클라우드 서비스 기반 CRM &amp; 브로드씨엔에스</strong> 등의 서비스에서 백엔드 및 웹 서비스 개발 구축 등을 해왔습니다.<br />
          <mark>서비스 운영에 도움이 되는</mark> 개발을 해야한다는 생각에 고객의 니즈를 분석하고 기능 개선을 통해 유지보수 계약을 확대하여 <mark>회사 수익</mark>에 기여하였으며,
          기존 시스템 개발 과정에 TDD를 도입하여 시스템 개발에 안정성을 향상 시켰습니다
          .<br /><br />
          팀원들과 협력하여 더 나은 환경과 우수한 시스템을 개발하는 데 큰 만족감을 느끼며 업무 수행하며, <br/>더 나은 코드를 위해 <strong>팀원 간의 소통</strong>을 중요시합니다.
        </p>


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
